### ISSUE TITLE
computeCodePhase

### ISSUE THREAD

**Issue by robellebor** [osqzss/gps-sdr-sim#107]
// Initial code phase and data bit counters.
	ms = ((subGpsTime(chan->rho0.g,chan->g0)+6.0) - chan->rho0.range/SPEED_OF_LIGHT)*1000.0;

	ims = (int)ms;
	chan->code_phase = (ms-(double)ims)*CA_SEQ_LEN; // in chip

what is the reason that ms is changed to int and back to double, and subtracted ims from ms ?? 
And what is ms and ims ??

**Comment by osqzss** [comment]
To obtain fractional parts of a millisecond.
