### ISSUE TITLE
C/A code generation...code chip delay

### ISSUE THREAD

**Issue by bikilay** [osqzss/gps-sdr-sim#109]
in ca code generation, when code selection takes place how 2 XOR 6 form code chip delay of 5, and 3 XOR 7 forms 6 etc....how these delays created??

**Comment by osqzss** [comment]
You don't need the both. The delay in the G2 generator is equivalent to the XOR of the selected taps.  You can implement the code generator in either way.

**Comment by bikilay** [comment]
that is ok..but i don not understand how delay in G2 generator formed...how 2 XOR 6 form 5 delay..??
    my point is how these delays are formed with code selections??

**Comment by osqzss** [comment]
I don't know the exact way to convert a given phase delay into a pair of XOR taps, but it is known as "shift and add" property of any m-sequence. The different pairs of XOR taps yield the same m-sequence with different delays.

**Comment by bikilay** [comment]
ok thanks
