### ISSUE TITLE
constant value

### ISSUE THREAD

**Issue by kasmf** [osqzss/gps-sdr-sim#114]
what is the constant value of POW2_M29 and others ... how we get those values? is it constant or determined...

**Comment by osqzss** [comment]
Take a look into the scale factors of almanac and ephemeris parameters in Tables 20-I and 20-III of ICD-200C: https://www.navcen.uscg.gov/pubs/gps/icd200/ICD200Cw1234.pdf

**Comment by kasmf** [comment]
thank you for u replay .... 
what is scale factor of the LSB ... how to determine LSB value

**Comment by Honky103** [comment]
Strongly recommend u refer to the ICD document posted above. It contains all the scale factor for all parameters in the subframes

**Comment by osqzss** [comment]
The parameter value is obtained by multiplying each bit by its scaling factor.
