### ISSUE TITLE
wna and toa

### ISSUE THREAD

**Issue by kasmf** [osqzss/gps-sdr-sim#115]
how to get the value of 256 and 4096 in those wna = (unsigned long)(eph.toe.week%256) and toa = (unsigned long)(eph.toe.sec/4096.0) code ... it is not clear whether it is constnant or determined for me.

**Comment by osqzss** [comment]
Please refer sections 20.3.3.5.1.7 and 20.3.3.5.2.2 of ICD-200C about almanac reference time.
