### ISSUE TITLE
tx

### ISSUE THREAD

**Issue by robellebor** [osqzss/gps-sdr-sim#129]
/usr/lib/uhd/examples/tx_samples_from_file --args="master_clock_rate=50e6" --file gpssim.bin --type short --rate 2500000 --freq 1575420000 --gain 0 --repeat
this code is giving me
      setting TX Rate:2.500000 Msps...
      Segmentation fault (core dumped)

**Comment by osqzss** [comment]
The segmentation fault was cased by the UHD tool, not the baseband file generated by gps-sdr-sim.
Try to analyze the core dump with gdb, or post your question to USRP-users mailing list.
http://lists.ettus.com/mailman/listinfo/usrp-users_lists.ettus.com
