### ISSUE TITLE
receiving gps signal

### ISSUE THREAD

**Issue by bikilay** [osqzss/gps-sdr-sim#133]
from gps sdr simulation, i could transmitting using USRP N200.  it is transmitting well but when i tried to receive using GPS Data application on my phone, i faced a problem. i could not receive the signals even if able to transmit. ...how can i probably fix?

![here](https://user-images.githubusercontent.com/33923635/37021709-8e040d24-2131-11e8-99cf-91d8e0b8ffe3.png)

**Comment by osqzss** [comment]
The default sampling frequency of gps-sdr-sim is 2.6MHz. If you want to transfer the I/Q samples at 2.5MHz, the sampling frequency of the gps-sdr-sim has to be set to the same value with '-s' option.

**Comment by bikilay** [comment]
ok when am using 2.6MHz, it says like this:
  UHD Warning:
    The hardware does not support the requested TX sample rate:
    Target sample rate: 2.600000 MSps
    Actual sample rate: 2.631579 MSps
Press Enter to quit: 

![screenshot from 2018-03-06 17-05-12](https://user-images.githubusercontent.com/33923635/37036765-aa216486-2161-11e8-9026-41d737aed953.png)

**Comment by HansHoogerwerf** [comment]
> HackRF and bladeRF require 2.6 MHz sample rate, while the USRP2 requires 2.5 MHz (an even integral decimator of 100 MHz).

 Maybe you want to try 2.5?

**Comment by osqzss** [comment]
I mean '-s' option of gps-sdr-sim.

**Comment by alkuna** [comment]
Besides the correct sampling frequency, I see two other possible problems:

1. Is 5-min record sufficient to provide full navigation and time messages?
2. Are you sure your phone is not confused when receiving GPS signal with date and time 4 years in the past?

Could you please try to download more recent brdc file and generate a file with 30 minutes of data?
