### ISSUE TITLE
Receive GPS data error!!

### ISSUE THREAD

**Issue by CodoonAutomatedTest** [osqzss/gps-sdr-sim#135]
from gps sdr simulation, I could transmitting using hackrf One.it is transmitting well and i could receive the signals well, but when I used GPS Data application on HUAWEI Android phone(Kirin CPU). The GPS Data is different from another phone, The receive data is not available for data transmission. how can i probably fix?

**Comment by Fles42** [comment]
Do you tried turn on a fly mode?

**Comment by CodoonAutomatedTest** [comment]
@Fles42 yeah, I tried turn on a fly mode, and positioning method chose GPS Only

**Comment by osqzss** [comment]
The local oscillator frequency offset of HackRF One is rather large. Try to use a more precise external clock or kalibrate-hackrf.
https://github.com/scateu/kalibrate-hackrf
