### ISSUE TITLE
Real Time Streaming to HackRF

### ISSUE THREAD

**Issue by mtoan2111** [osqzss/gps-sdr-sim#137]
I have seen an issue at here: https://github.com/osqzss/gps-sdr-sim/wiki/Real-Time-Streaming-to-HackRF
The command: 
```
gps-sdr-sim -e brdcXXXX.17X -l 50.059330, 0.008319,100 -b 8 -T$(date +%Y/%m/%d,%H:%M:%S) -i -o gpsstream
```
should be changed:
```
gps-sdr-sim -e brdcXXXX.17X -l 50.059330, 0.008319,100 -b 8 -T now -i -o gpsstream
```
Thanks,
Toan

**Comment by osqzss** [comment]
Anyone can edit the Wiki pages. Your contributions are welcome!
