### ISSUE TITLE
Not compile on Linux

### ISSUE THREAD

**Issue by sgk** [osqzss/gps-sdr-sim#14]
> for (int i=1;i<numd;i++)

The declaration in the "for" directive requires C99 or C11 compiler. Do you accept this?

**Comment by sgk** [comment]
Merge #15 if you accept the C99 standard.

**Comment by sgk** [comment]
Merge #16 if you keep the ANSI conformance.

**Comment by osqzss** [comment]
I prefer using the old ANSI conformance. Thank you for the fix.

**Comment by sgk** [comment]
Thank you!
