### ISSUE TITLE
How to simulate a carrier frequency error...

### ISSUE THREAD

**Issue by ids-sdr** [osqzss/gps-sdr-sim#150]
Hallo, I would like to generate a GPS signal affected by a carrier frequency error.
To do so, I changed the following code-lines.
Within gpssim.h:

// My change 11/06/2018 -----------------------------------------------------------------
#define FREQ_ERROR		(3080.0)						//frequency error (Hz)
#define CARR_FREQ 		(1575.42e6 + FREQ_ERROR)		//L1 + freq. error (Hz)
#define LAMBDA_L1 		(SPEED_OF_LIGHT / CARR_FREQ)	//wavelength (m)
#define CARR_TO_CODE 	(1.0/1540.0)					//carrier-to-code ratio 
#define CODE_FREQ 		(CARR_TO_CODE * CARR_FREQ)		//chip rate with freq. error (Hz)
//----------------------------------------------------------------------------------------
	 
//
/*
#define LAMBDA_L1 0.190293672798365
//! \brief GPS L1 Carrier frequency 
#define CARR_FREQ (1575.42e6)
//! \brief C/A code frequency 
#define CODE_FREQ (1.023e6)
#define CARR_TO_CODE (1.0/1540.0)
*/

where FREQ_ERROR is the desired frequency error that should affect the L1.
Within gipssim.c:

void computeCodePhase(channel_t *chan, range_t rho1, double dt)
{
	double ms;
	int ims;
	double rhorate;
	
	// Pseudorange rate.
	rhorate = (rho1.range - chan->rho0.range)/dt;

	// Carrier and code frequency.
	chan->f_carr = -rhorate / LAMBDA_L1;
	chan->f_code = CODE_FREQ + chan->f_carr*CARR_TO_CODE;
	chan->f_carr = chan->f_carr + FREQ_ERROR;		//my change 11/06/2018
....

in this way the frequency error should have an impact on the carrier frequency, Doppler shift, and code phase computation. Is it right?

Nevertheless i tested the signal that was generated after this modification and it seems not able to be correctly received by my GNSS receiver...
Maybe I am forgetting anything? What do you think it is going wrong?
I have to change anything else (maybe the sine/cosine table)?

Thank you very much in advance!
Bye

**Comment by sliencefade** [comment]
So how did you solve it in the end?
