### ISSUE TITLE
gps-sdr-sim-uhd.py generating an error

### ISSUE THREAD

**Issue by karanjarich** [osqzss/gps-sdr-sim#154]
I* have tried to run this script on windows cmd 
C:\Users\production\Desktop\flexsdr\gps-sdr-sim-uhd.py
 but unfortunately am getting this error
Traceback (most recent call last):
  File "C:\Users\production\Desktop\flexsdr\gps-sdr-sim-uhd.py", line 6, in <mo
ule>
    from gnuradio import blocks
ImportError: No module named 'gnuradio'

**Comment by bitdust** [comment]
you need to install gnuradio
as far as i know,  it's ONLY officially support on linux
