### ISSUE TITLE
msys2,complie error

### ISSUE THREAD

**Issue by yangkkokk** [osqzss/gps-sdr-sim#162]
use win lib

lib path 
#include <C:\libiio\include\iio.h>
#include <C:\libad9361-win64\ad9361.h>

# make plutoplayer
Package libiio was not found in the pkg-config search path.
Perhaps you should add the directory containing `libiio.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libiio' found
Package libad9361 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libad9361.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libad9361' found
cc -g -o plutoplayer plutoplayer.o  -lm
plutoplayer.o：在函数‘main’中：
/j/gps-sdr-sim/player/plutoplayer.c:128：对‘iio_create_default_context’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:128:(.text.startup+0x2f9):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_create_default_context
/j/gps-sdr-sim/player/plutoplayer.c:147：对‘iio_create_scan_context’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:147:(.text.startup+0x30e):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_create_scan_context
/j/gps-sdr-sim/player/plutoplayer.c:149：对‘iio_scan_context_get_info_list’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:149:(.text.startup+0x323):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_scan_context_get_info_list
/j/gps-sdr-sim/player/plutoplayer.c:154：对‘iio_scan_context_destroy’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:154:(.text.startup+0x333):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_scan_context_destroy
/j/gps-sdr-sim/player/plutoplayer.c:158：对‘iio_context_get_devices_count’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:158:(.text.startup+0x347):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_context_get_devices_count
/j/gps-sdr-sim/player/plutoplayer.c:236：对‘iio_context_find_device’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:236:(.text.startup+0x38d):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_context_find_device
/j/gps-sdr-sim/player/plutoplayer.c:236：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:236:(.text.startup+0x3a2):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_device_find_channel
/j/gps-sdr-sim/player/plutoplayer.c:235：对‘iio_channel_attr_write_bool’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:235:(.text.startup+0x3b7):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_channel_attr_write_bool
/j/gps-sdr-sim/player/plutoplayer.c:240：对‘iio_channel_disable’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:240:(.text.startup+0x3c4):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_channel_disable
/j/gps-sdr-sim/player/plutoplayer.c:241：对‘iio_channel_disable’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:241:(.text.startup+0x3d1):  截断重寻址至相符: R_X86_64_PC32 针对未定义的符号 iio_channel_disable
/j/gps-sdr-sim/player/plutoplayer.c:242：对‘iio_context_destroy’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:242:(.text.startup+0x3d9):  从输出所省略的额外重寻址溢出
/j/gps-sdr-sim/player/plutoplayer.c:166：对‘iio_context_find_device’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:173：对‘iio_device_set_kernel_buffers_count’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:175：对‘iio_context_find_device’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:176：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:177：对‘iio_channel_attr_write’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:178：对‘iio_channel_attr_write_longlong’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:179：对‘iio_channel_attr_write_longlong’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:180：对‘iio_channel_attr_write_double’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:183：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:182：对‘iio_channel_attr_write_bool’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:187：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:186：对‘iio_channel_attr_write_longlong’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:191：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:195：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:200：对‘iio_channel_enable’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:201：对‘iio_channel_enable’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:203：对‘iio_context_find_device’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:203：对‘ad9361_set_bb_rate’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:207：对‘iio_device_create_buffer’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:214：对‘iio_context_find_device’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:214：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:213：对‘iio_channel_attr_write_bool’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:218：对‘iio_buffer_start’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:225：对‘iio_buffer_push’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:236：对‘iio_context_find_device’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:236：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:235：对‘iio_channel_attr_write_bool’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:239：对‘iio_buffer_destroy’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:131：对‘iio_create_network_context’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:140：对‘iio_strerror’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:151：对‘iio_context_info_get_description’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:152：对‘iio_context_info_list_free’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:133：对‘iio_create_context_from_uri’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:168：对‘iio_strerror’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:197：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:193：对‘iio_device_find_channel’未定义的引用
/j/gps-sdr-sim/player/plutoplayer.c:135：对‘iio_create_network_context’未定义的引用
collect2: 错误：ld 返回 1
make: *** [Makefile:25：plutoplayer] 错误 1

**Comment by osqzss** [comment]
Please follow the instructions in the README.md.
