### ISSUE TITLE
One plus 6T can't be deceived

### ISSUE THREAD

**Issue by K1two2** [osqzss/gps-sdr-sim#185]
One plus 6T can't deceive, I turned on the flight mode and always showed "GPS positioning".

![0114192048](https://user-images.githubusercontent.com/9145406/51114024-035ddc80-183f-11e9-8f86-a2496aa1a828.jpg)

![0114192048_hdr](https://user-images.githubusercontent.com/9145406/51113972-d6112e80-183e-11e9-871d-cc40c1266f2f.jpg)

**Comment by osqzss** [comment]
They are getting smarter :)

**Comment by kitwou** [comment]
@osqzss is there any way we can lock these devices with spoofed signals? like jamming BDS and other GNSS? i have noticed some newer devices locks with our GPS when we switch to airplane mode and reboot (no data connection after reboot), can you explain in detail if possible what measures should i take to make these devices lock?
hardware used: bladeRF, hackrf, USRP - B210.

**Comment by dkdhruv123** [comment]
can you tell me on what basis these phones ignore our spoofed signals? or what can i do to make these phones lock to mine signal? jamming each and every BDS and glonass? transmit at more power ? 
one thing i have noticed that when i switch on airplane mode and reboot (no cellular connection after reboot), these phones get locked within 1 minute but not with cellular/wifi turned on. any solutions ?

**Comment by Shangu-xsg** [comment]
Hello, can you tell me what SDR you use to complete GPS spoofing? Also, do you have an external antenna on the SDR? During my GPS spoofing, the signal I received from the GPS was always too weak.
