### ISSUE TITLE
Receiving signals but co-ordinates remain unchanged.

### ISSUE THREAD

**Issue by r00tb3** [osqzss/gps-sdr-sim#198]
My smartphone is receiving signals but the location is undetected.

![WhatsApp Image 2019-06-20 at 1 11 42 PM](https://user-images.githubusercontent.com/24567198/59832568-d4a1e000-9361-11e9-9cca-9c2eb1956513.jpeg)
![WhatsApp Image 2019-06-20 at 12 58 43 PM](https://user-images.githubusercontent.com/24567198/59832569-d4a1e000-9361-11e9-9991-29d0f4ea0b9e.jpeg)

What might be the problem?

@osqzss

**Comment by Johsnon** [comment]
Hi,
what SDR device is this? Hackrf? Is there an additional TCXO (=clock) installed?
![TCXO](https://images-na.ssl-images-amazon.com/images/I/71Nm1ONqMOL._SY355_.jpg)
I had the same problem, because the clock of my hackrf wasn't precise enough.

**Comment by r00tb3** [comment]
> Hi,
> what SDR device is this? Hackrf? Is there an additional TCXO (=clock) installed?
> ![TCXO](https://camo.githubusercontent.com/1bd860bd6245df47eb5609a9721d23aa58e6fd67/68747470733a2f2f696d616765732d6e612e73736c2d696d616765732d616d617a6f6e2e636f6d2f696d616765732f492f37314e6d314f4e714d4f4c2e5f53593335355f2e6a7067)
> I had the same problem when using hackrf without that clock part (the internal clock of my hackrf wasn't precise enough).

It's HackRF and I'm not using an external clock with the HackRF.

Where can I buy the external clock that you've mounted on the HackRF?

Also, will I need a passive GPS antenna?

**Comment by osqzss** [comment]
You can make one by yourself ;)
https://github.com/osqzss/gps-sdr-sim/tree/master/extclk

**Comment by osqzss** [comment]
A simple dipole antenna works just fine.
https://www.u-blox.com/sites/default/files/products/documents/GPS-Antenna_AppNote_%28GPS-X-08014%29.pdf

**Comment by r00tb3** [comment]
Following this [setup](https://github.com/osqzss/gps-sdr-sim/blob/master/extclk/hackrf_gpssim.jpg) I'm buying a [passive GPS antenna](http://www.digikey.com/product-search/en?keywords=TS.07.0113), [RF attenuator](https://www.mouser.in/ProductDetail/HUBER%2bSUHNER/6630_SMA-50-2-199_NE?qs=sGAEpiMZZMvo7grblV%252BRTALl1QIn%252BZZTdTmTBD6cXrygPAKU7ITuMQ%3D%3D) & [TCXO Module](https://www.nooelec.com/store/tiny-tcxo.html).

Also, do I need the 30db attenuator as shown [here](https://github.com/osqzss/gps-sdr-sim/blob/master/extclk/hackrf_gpssim.jpg)?

What if I don't use the attenuator?

**Comment by osqzss** [comment]
It will disturb the GPS receivers in your neighborhood.

**Comment by r00tb3** [comment]
> Hi,
> what SDR device is this? Hackrf? Is there an additional TCXO (=clock) installed?
> ![TCXO](https://camo.githubusercontent.com/1bd860bd6245df47eb5609a9721d23aa58e6fd67/68747470733a2f2f696d616765732d6e612e73736c2d696d616765732d616d617a6f6e2e636f6d2f696d616765732f492f37314e6d314f4e714d4f4c2e5f53593335355f2e6a7067)
> I had the same problem when using hackrf without that clock part (the internal clock of my hackrf wasn't precise enough).

Did you also change the antenna? Or just used provided an external clock of 10Mhz and it worked?

**Comment by kozlovsas** [comment]
I'm having a similar issue where my car's GPS is receiving the signal but is not changing location. I'm using a HackRF with a TXCO module from NooElec, and an ANT500 in a controlled environment. The same occurs with my smartphone- I've turned off Wifi/Cellular/Bluetooth and when I launch Google Maps my location is not changed. I'm just broadcasting a static location, should I broadcast something else?

**Comment by ogord** [comment]
Hi, I have the same problem, but with LimeSDR. I use the next parameters:
./gps-sdr-sim -e brdc1850.19n -s 2500000 -l 35.170514,25.009579,100 -b 8 -o sim111.bin
./limeplayer -s 2500000 -b 8 -g 0.5 < ../sim111.bin 
Device configuration:
os ubuntu 16.04
LimeUtil --info
 Version information:
  Library version:	v19.04.0-gd20557de
  Build timestamp:	2019-07-04
  Interface version:	v2019.1.0
  Binary interface:	19.04-1
SoapySDRUtil --info
Lib Version: v0.8.0-gfe8dfd18
API Version: v0.8.0
ABI Version: v0.8
Install root: /usr/local
Search path:  /usr/local/lib/SoapySDR/modules0.8
Module found: /usr/local/lib/SoapySDR/modules0.8/libLMS7Support.so (19.04.0-d20557d)
Available factories... lime
Available converters...
 -  CF32 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS16 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS32 -> [CS32]
 -   CS8 -> [CF32, CS16, CS8, CU16, CU8]
 -  CU16 -> [CF32, CS16, CS8]
 -   CU8 -> [CF32, CS16, CS8]
 -   F32 -> [F32, S16, S8, U16, U8]
 -   S16 -> [F32, S16, S8, U16, U8]
 -   S32 -> [S32]
 -    S8 -> [F32, S16, S8, U16, U8]
 -   U16 -> [F32, S16, S8]
 -    U8 -> [F32, S16, S8

**Comment by r00tb3** [comment]
> I'm having a similar issue where my car's GPS is receiving the signal but is not changing location. I'm using a HackRF with a TXCO module from NooElec, and an ANT500 in a controlled environment. The same occurs with my smartphone- I've turned off Wifi/Cellular/Bluetooth and when I launch Google Maps my location is not changed. I'm just broadcasting a static location, should I broadcast something else?

I guess you'll ahve to get a GPS antenna I doubt if ANT500 will work!!

**Comment by osqzss** [comment]
@r00tb3 
The signal strength shown in your picture seems too low. They should be somewhere around 45dB.
By the way, the nominal TX power of HackRF or any other SDR devices is very high. You can use ANT500 to transmit the GPS signal without any trouble.

**Comment by r00tb3** [comment]
I've mounted the TXCO module and a GPS antenna so now the spoofing attack works!!

**Comment by kozlovsas** [comment]
Thanks @osqzss for confirming the ANT 500 will indeed work, I figured that made no sense why it wouldn't. I'll open a separate issue for my case.
