### ISSUE TITLE
Possible doppler effect error high speeds

### ISSUE THREAD

**Issue by DL7AD** [osqzss/gps-sdr-sim#202]
Hi,

I'm trying to simulate high altitude situations. I used the rocket.csv and satellite.csv demos therefore. When the simulation is not moving everything works fine but as it gets drastically fast (like above 500m/s), my receiver loses GPS lock. It locks shortly as the rocket get slower as it reaches the top of ascent. Could there something be wrong with the doppler effect which is calculated according to those speeds? Simulating static locations doesn't pose a problem.

Sven

**Comment by osqzss** [comment]
You need a very special receiver to overcome that speed limit.
https://space.stackexchange.com/questions/14687/current-situation-with-cocom-regulations-and-gps-receivers-for-balloons-and-cube

**Comment by DL7AD** [comment]
I have that kind of receiver.

**Comment by osqzss** [comment]
I've tested several different space-capable GPS receivers with my gps-sdr-sim demo scenarios but never had a similar trouble. Do you mind if I ask which GPS receiver you have?

**Comment by DL7AD** [comment]
This was not an error by the gps simulator rather than the signal strength at the GPS receiver. There are still problems receiving it, but the cause lays at the receiver itself.
