### ISSUE TITLE
Problem with generating .bin file

### ISSUE THREAD

**Issue by alex512125** [osqzss/gps-sdr-sim#207]
Hello!I have tried to transmit some location with my HackRF but GPS Test at android phone even don t see any strong signals  ! I searching in other issues and found out that .bin works perfectly for me (https://github.com/osqzss/gps-sdr-sim/issues/33#issuecomment-189151493) .It fix location in 30 seconds.But when i generate .bin by gps-sdr-sim phone even dont see signals from HackRF!!
PS.I am using Ubuntu 19.04

**Comment by alex512125** [comment]
![tem1psnip](https://user-images.githubusercontent.com/53433241/62049455-f2434e80-b217-11e9-815d-c7a09c1a6bfb.png)
In sdr#
I use Ubuntu 19.04

**Comment by osqzss** [comment]
Show us the command line that you executed.

**Comment by alex512125** [comment]
hackrf_transfer -t test.bin -f 1575420000 -s 2600000 -a 1 -x 0

Thats your firmware from comment 33
https://drive.google.com/drive/folders/0B36BcNBXEPjzUmlxX1dYUVRsT00

**Comment by osqzss** [comment]
I mean the command line options of gps-sdr-sim.

**Comment by osqzss** [comment]
You need "-b 8" option to generate 8-bit I/Q stream for HackRF.

**Comment by alex512125** [comment]
Thank you very much.Now it shows signals!!
