### ISSUE TITLE
visibility of satellite only checked in static mode

### ISSUE THREAD

**Issue by laf0rge** [osqzss/gps-sdr-sim#21]
As far as I can tell, the visibility check of a satellite seems to be performed only once at startup of the program, and not continuously during dynamic mode with user motion data.

This means that a satellite might disappear behind the horizon during runtime, but we still generate its PRN sequence and report it to the receiver.

**Comment by osqzss** [comment]
Yes, I know this issue. I am working on a real-time version, and a satellite visibility check thread will be added to it.
