### ISSUE TITLE
limitation to 300 seconds

### ISSUE THREAD

**Issue by laf0rge** [osqzss/gps-sdr-sim#22]
The code contains some static array of user motion data for 300 seconds at 0.1 Hz rate.  This restricts the use case to very short time frames only.
I would want to modify the code to accept a stream of user motion data (without limit in time). The array would be gone, and instead motion data be read 'as needed' rather than pre-reading + buffering all of it during start-up.
Would you be interested in merging such a patch?

**Comment by osqzss** [comment]
Yes, continuous signal generation is very attractive, and that's something I am currently working on. If you already have working code, I live to test it.

**Comment by laf0rge** [comment]
I don't yet have code, but would be willing to help.  As you are alrady working on it, I will wait for it to appear in some branch of your repository, to avoid any duplication.

**Comment by sinak** [comment]
Hi there, I'm actually using a static location, and I'm wondering why there's a limit to 300 seconds. Would there be any issues with increasing this?

**Comment by bitdust** [comment]
@sinak  
I'm working on the realtime version of gps-sdr-sim and then find the way to modify the limitation for static location mode.
#62

**Comment by sinak** [comment]
Ah wonderful, thanks @bidtust. I modified the 300 number manually and recompiled and it seems to work just fine.

Have you seen @osqzss's attempt at real-time for BladeRF? https://github.com/osqzss/bladeGPS
