### ISSUE TITLE
Reference for the implementation

### ISSUE THREAD

**Issue by KAUSHAL1986** [osqzss/gps-sdr-sim#227]
I want to clearly understand what is being done in function "computeCodePhase" and how does this spoofs the co-ordinates of the target. Which paper is used to implement this method . 

With Thanks and Regards
KAUSHAL KUMAR

**Comment by KAUSHAL1986** [comment]
Got it

**Comment by Imtiaz08** [comment]
Kaushal1986 can you please provide the info to me too? I am also trying to learn the same thing... 

I will be very thankful to you for this act of kindness
