### ISSUE TITLE
Please help me understanding with the gpssim.c code

### ISSUE THREAD

**Issue by komalkumar6655** [osqzss/gps-sdr-sim#282]
hello, i am a student. I am trying to understand the gpssim.c code . Please any body help  me.....!!!!!

**Comment by Mictronics** [comment]
Should we guess your problems?
Why don't you ask specific question related to the code?

**Comment by komalkumar6655** [comment]
Thank you.
I am having trouble in understanfing the generation of navigation message from ephemris data.
Pleae help me...

**Comment by komalkumar6655** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/50194222/108148628-3ac2a580-70f7-11eb-82ab-bf4fe98ce653.png)

**Comment by komalkumar6655** [comment]
Can anybody expalin the subframe 1 in the above picture. How subframe 1 is generated.
thankyou.

**Comment by osqzss** [comment]
You can find all the definitions of the message structure and contents in IS-GPS-200.
https://www.gps.gov/technical/icwg/

**Comment by komalkumar6655** [comment]
Thank you for response. 
Can you expalin this 0X8B0000UL<<6 mean .
please.......

**Comment by osqzss** [comment]
It's a preamble.
![preamble](https://user-images.githubusercontent.com/7418842/108152280-0f9e7d00-711c-11eb-8951-5d826fa1c32f.png)

**Comment by komalkumar6655** [comment]
Thanks
But why are you shifting it 6 times

**Comment by komalkumar6655** [comment]
Please Explain this 
I will be Thankful to you.

**Comment by ongbuntu** [comment]
> Please Explain this 
> I will be Thankful to you.
> 

Each word is 30bits long. 0x8B is the hex representation of the premble. By shifting 6bits to the left, you would put the premble in the right bits position withing the TLM word.

**Comment by ongbuntu** [comment]
To learn the code, I strongly suggest that you first read the ICD and understand how each word is packed and what the individual parameters mean. Once you are able to understand one word, the rest of the code will start to flow.

**Comment by komalkumar6655** [comment]
Thank you for your response..
But why to shift 6 times as the preamble is 0X8B == 10001011 .
Why to shift it 6 times . 
there is no information about this in the given document .
Please explain 
I will be very thankful.

**Comment by komalkumar6655** [comment]
Please any one respond to the above comment.
Please......

**Comment by Mictronics** [comment]
See the comment above from ongbuntu. In addition of aligning the preamble on MSB with <<6 you make up the space for the 6 bit parity on the LSB (left).

**Comment by komalkumar6655** [comment]
Sorry I didnot understand .
can You please explain again..

**Comment by k4cle** [comment]
Hello Tak,
I hope you and all yours are staying well during this Covid plague.  Long time no see!
All good here - just got my second vaccine shot so maybe I can get out and go to a restaurant or something before long!
Take care, hope to see you at one of the ION shows or some GPS event before long.
Doug BakerGPS Creations


-----Original Message-----

**Comment by Mictronics** [comment]
@komalkumar6655 

> Can you expalin this 0X8B0000UL<<6 mean .

First look at the constant 0x8B0000UL. You will notice it's not a 32bit representation but 24bit (6 digits not 8), so in 32bit that's 0x008B0000UL.
```
0x008B0000UL
0000 0000 1000 1011 0000 0000 0000 0000
<< 6
xx10 0010 1100 0000 0000 0000 00pp pppp <  p = 6 parity bits

The entire TLM word is only 30 bits long (24 data + 6 parity).
So the upper two MSB (xx) are not relevant.

After <<6 the preamble 8B is MSB left aligned as required in spec.
```

**Comment by komalkumar6655** [comment]
Thank you very much for your kind response.

**Comment by Mictronics** [comment]
Did you ever read the IS-GPS-200 that was mentioned in a previous post?

(Ignore the 0 above word 1, edit mistake)
![image](https://user-images.githubusercontent.com/11965780/108241853-8f444000-714c-11eb-8cfd-1e770ac3c857.png)
WN is in word 3 of subframe 1, bit position 71 in the **entire frame**.
The pink numbers in my paste are the word length and LSB in code. You see that LSB bit 1 of word 3 corresponds to bit 91 in subframe 1. Hence you need to shift <<20 (91-71=20) to place "wn" at the correct bit position in word 3 and therefore at the correct bit position in the entire frame.

PS: Maybe you should change your student class for gardening...

**Comment by komalkumar6655** [comment]
since you have already studied the code and designed a new repository for multiple GPS SDR SIM.
I  am new to this GPS simulator and i didnot understand the logic behind it . Thats why I have asked many times about that.
