### ISSUE TITLE
Why is data in ephemeris divided by POW2_M*?

### ISSUE THREAD

**Issue by yangfan852219770** [osqzss/gps-sdr-sim#297]
In **eph2sbf** function, I don't understand why is some data read from the ephemeris divided by POW2_M*? 
Like this:
`cuc = (long)(eph.cuc/POW2_M29);`

**Comment by Mictronics** [comment]
POW2_M* is a scale factor. See IS-GPS-200L for details. Table 20-III Ephemeris parameters. gpssim.h has the corresponding scale factors.

**Comment by yangfan852219770** [comment]
Oh, my god! This is a stupid question! Because they have **Scale Factor**.
