### ISSUE TITLE
How can I generate  GLONASS  signal too?

### ISSUE THREAD

**Issue by 20140067** [osqzss/gps-sdr-sim#298]
Thank you very much for your gps-sdr-sim.  
How can I generate  GLONASS  signal too？

**Comment by TachyonZZ** [comment]
Start here https://russianspacesystems.ru/wp-content/uploads/2016/08/ICD-GLONASS-CDMA-General.-Edition-1.0-2016.pdf
Then start coding. 
The two constellations aren't similar and this repo will do you little good simulating GLONASS.

**Comment by 20140067** [comment]
I see, thank you very much!

**Comment by Retinaaa** [comment]
@MAVProxyUser @osqzss @ TachyonZZ
do you know any kind of system or code that can generate GLONASS signals?
