### ISSUE TITLE
Generating ECEF

### ISSUE THREAD

**Issue by vsboost** [osqzss/gps-sdr-sim#3]
This is not an issue more a question, what are you using to generate the ecef data? are there any programs that are freely available that can do it?
Ill close this once you reply.

Thanks

**Comment by osqzss** [comment]
I couldn't find any free software to generate user trajectory, either. There are few commercial products, such as SimGen for LabSat and SimROUTE for Spirent simulator.

**Comment by osqzss** [comment]
I have just found out a free NMEA simulator from LabSat:
http://www.labsat.co.uk/index.php/jp/free-gps-nmea-simulator-software

This can be used to generate an ECEF user motion file for gps-sdr-sim.
I will give it a shot.

**Comment by osqzss** [comment]
It works nicely! Give a quick look into the tools folder.

**Comment by vsboost** [comment]
This works perfectly, thanks for your hard work..
