### ISSUE TITLE
Galileo Constellation Simulation.

### ISSUE THREAD

**Issue by AntI-HI** [osqzss/gps-sdr-sim#304]
Are You planning to simulate the signal structure for Galileo Constellation? If not How can I achieve it like this GPS sdr Sim? Where can I learn the details of Galileo signal structure and data structure?

**Comment by osqzss** [comment]
Galileo Open Service Signal in Space Interface Control Document tells you all.
https://www.euspa.europa.eu/newsroom/news/updated-galileo-os-sis-icd-now-available

**Comment by FayeWong98** [comment]
Hello, have you realized Galileo's signal attack?

**Comment by AntI-HI** [comment]
> Hello, have you realized Galileo's signal attack?

Hello, I have quitted this field almost a year ago. So I couldn't finish it.
