### ISSUE TITLE
Running GPS-SDR-SIM without adding noise

### ISSUE THREAD

**Issue by fener1efes2** [osqzss/gps-sdr-sim#337]
GPS-SDR-SIM adds noise in band purposefully.
I want to observe its BPSK signal.
How can I turn off adding noise property?

![image](https://user-images.githubusercontent.com/107809055/187061036-d4fb3789-a645-47ba-8de5-334b2dd1e2d2.png)

**Comment by osqzss** [comment]
gps-sdr-sim generates pure baseband signals. No noise is added.

**Comment by fener1efes2** [comment]
> gps-sdr-sim generates pure baseband signals. No noise is added.

I shared output of the HackRF transmitting signal produced by the GPS-SDR-SIM. 
As you can see, the waveform is not as it is expected.
I would expect a waveform as shown below.
 
![image](https://user-images.githubusercontent.com/107809055/187064694-3bf1377a-9cf8-49f5-836c-dfcf3972b767.png)

**Comment by osqzss** [comment]
Yes, that's exactly what you can expect to see. It seems that the HackRF did not transmit the baseband samples properly. You have to set the I/Q sample format to 8-bit with -b option for the HackRF.

**Comment by aeaotst** [comment]
I get similar results using the USRP B200 mini-i regardless of whether I use 16-bit or 8-bit. My receiver is reading the signal and getting a fix so perhaps not an issue, though I have to wonder if there's any implication for C/N.

**Comment by osqzss** [comment]
Here's a sample PSD plot of the L1 C/A signal with a 2.6MHz sampling rate and a 2.5MHz double-side bandwidth. You can see the main lobe on center and partial side lobes on both ends.

![PXL_20210104_032442100](https://user-images.githubusercontent.com/7418842/187229257-92ccd18e-45c5-4956-971e-2903603a66f0.jpg)

**Comment by fener1efes2** [comment]
why is it so noisy? I tested another commercial GPS simulator and it gives an output as shown below. 

![image](https://user-images.githubusercontent.com/107809055/187359284-8cd98289-7c7e-47bc-9010-6d3fe774f6f3.png)

**Comment by fener1efes2** [comment]
> Here's a sample PSD plot of the L1 C/A signal with a 2.6MHz sampling rate and a 2.5MHz double-side bandwidth. You can see the main lobe on center and partial side lobes on both ends.
> 
> ![PXL_20210104_032442100](https://user-images.githubusercontent.com/7418842/187229257-92ccd18e-45c5-4956-971e-2903603a66f0.jpg)
@osqzss 
Is the bandwidth of the signal 3.6MHz? If I see the span correctly which is 6MHz, then the span must be 3.6MHz?

**Comment by Imtiaz08** [comment]
I think the transmitter and the receiver component added noise can't be neglected. Have you checked probing the signal in the software without transmitting it?

**Comment by IvanKor** [comment]
> I think  ...

GPS uses pseudo-noise 1023-bit  technology.

By connecting the output RF of the HackRF transmitter [Real-time GPS signal simulator based on GPS-SDR-SIM](https://github.com/IvanKor/hrfGPS) via an attenuator to the NEO-M8T antenna input for 1.5 hours and turning on all corrections Solution: SINGLE [RTKLIB](http://www.rtklib.com) make sure that during this time the total error (RMS) ~ 0.1 meters.

![](https://raw.githubusercontent.com/IvanKor/hrfGPS/master/outpu5_2_mhz2.jpg)

If use USRP B200 (16-bit) instead of HackRF (8-bit), then instead of RMS~0.1m get RMS<0.01m

**If your simulator has RMS>0.1m (1m or more) then this simulator is not correct.**
