### ISSUE TITLE
Sample rate for HackRF

### ISSUE THREAD

**Issue by fener1efes2** [osqzss/gps-sdr-sim#338]
As can be seen from [https://github.com/greatscottgadgets/hackrf/blob/master/host/hackrf-tools/src/hackrf_transfer.c](url), HackRF supports sample rate up to 20MHz.
`#define SAMPLE_RATE_MIN_HZ     (2000000)  /* 2MHz min sample rate */`
`#define SAMPLE_RATE_MAX_HZ     (20000000) /* 20MHz max sample rate */`
`#define DEFAULT_SAMPLE_RATE_HZ (10000000) /* 10MHz default sample rate */`

But on the GPS-SDR-SIM, it states that it need 2.6MHz sample rate, as can be seen from below.

![image](https://user-images.githubusercontent.com/107809055/188322641-fcacb7b2-db06-418c-b98b-97b6cc3a92e9.png)

Why do we need to use HackRF with 2.6MHz sample rate?

**Comment by osqzss** [comment]
It is not required. You can use any sample rate higher than a single-side bandwidth of the GPS baseband.
