### ISSUE TITLE
What is the format of the csv file

### ISSUE THREAD

**Issue by nzkarit** [osqzss/gps-sdr-sim#34]
Hi,

I'm looking at the circle.csv file and was wondering what each column was and what format it is in. Is there any documentation for it anywhere? I would like to make my own shape.

Thanks

**Comment by osqzss** [comment]
The CSV file needs to contain 10Hz user motion in the ECEF frame. The time stamps in the first column are not used in the simulator. You can use the llh2xyz function in the main code to transform your geographic position into the ECEF.

**Comment by nzkarit** [comment]
Thanks

**Comment by szakacsm** [comment]
Hi, if I have a user motion file in kml format how can I transform it to ECEF frame?

**Comment by osqzss** [comment]
Use llh2xyz function in gpssim.c.

**Comment by szakacsm** [comment]
in visual studio? how can I give the input (user motion) kml file? 
can you please give detailed explanation?
I am not an expert programming guy

**Comment by szakacsm** [comment]
I am getting to understand what you said
Please confirm the following
llh[0] = latitude
llh[1] = longitude
llh[2] = ???

**Comment by osqzss** [comment]
height
