### ISSUE TITLE
BRDC/Hourly data

### ISSUE THREAD

**Issue by ark-1313** [osqzss/gps-sdr-sim#343]
Hi,

We are using the CDDIS hourly/daily data for the navigation data generation. We wish to generate the data for the current UTC. However, from the downloaded data it says that the timing (TOC & TOE) are invalid and hence will not be able to generate for the required time. This requires us to wait until the new data is released from the cddis. If we try over-riding using the 'T' option, it is observed that the  receiver does not spoof at all.
1. Is there any other way through which the TOC/TOE can be modified to get the data for the current UTC from the hourly/brdc file ?
2. We came across another issue in which you suggested to use RTKLib with a receiver to process the raw data in order to obtain the ephemeridis. How long will the validity of a data obtained in such a manner be & how long should such a recording be done?

With Regards,
ARK.

**Comment by ark-1313** [comment]
Any help, anyone ?

**Comment by osqzss** [comment]
2. It requires only a 18-sec long navigation massage (subframe 1-3), which repeats every 30 seconds.

**Comment by ark-1313** [comment]
& we can generate data through the tool for the next 1 hour ?

What about (1) ?

**Comment by osqzss** [comment]
A broadcast ephemeris is typically valid for about two hours.
Regarding question 1, the answer is no.

**Comment by ark-1313** [comment]
Thanks a lot. Wonderful tool BTW !!
