### ISSUE TITLE
Adding white noise

### ISSUE THREAD

**Issue by fener1efes2** [osqzss/gps-sdr-sim#344]
I transmit the signals created by GPS-SDR-SIM by using HackRF.
I connected U-BLOX GPS L1 C/A receiver with cable to HackRF.
Naturally, C/No values of the GPS signal becomes so high like 55dB/Hz.
Is there a way that I can add white noise at the output of the HackRF while transmitting GPS signal created by GPS-SDR-SIM?

**Comment by osqzss** [comment]
Use attenuators.
