### ISSUE TITLE
Properties of ADALM-Pluto's DAC

### ISSUE THREAD

**Issue by fener1efes2** [osqzss/gps-sdr-sim#351]
ADALM-Pluto has a 12-bit DAC as can be seen from its web-site: https://wiki.analog.com/university/tools/pluto/devs/specs

![image](https://user-images.githubusercontent.com/107809055/196807969-40c26f7e-93e9-4791-90a5-305a6cde1cec.png)

But since we feed it with 16-bit integers, do not we overdrive its DAC?

![image](https://user-images.githubusercontent.com/107809055/196808231-d418d89f-d891-4c46-a611-9b149d16a1ab.png)

**Comment by osqzss** [comment]
A 12-bit DAC value is stored in a 16-bit integer.
