### ISSUE TITLE
Generate QZSS

### ISSUE THREAD

**Issue by kurokkasu** [osqzss/gps-sdr-sim#353]
I am making a QZSS signal.
The signal does not become the green used for positioning.
Please advise what should be changed.
![qzssnavi](https://user-images.githubusercontent.com/82863897/198968108-f8e00625-bbef-442d-bc83-9ff417e42496.PNG)

**Comment by osqzss** [comment]
It turns green when it is used in navigation. You never get valid 3D navigation fix with only three satellites.

**Comment by kurokkasu** [comment]
How do I know if it's the correct signal?

**Comment by osqzss** [comment]
Add GPS satellites.

**Comment by kurokkasu** [comment]
If gps is added and qzss turns green, does that mean it's okay?

**Comment by osqzss** [comment]
Plus you have to get proper navigation solutions.

**Comment by osqzss** [comment]
Would you please send a pull request to add your QZSS signal generation code to the gps-sdr-sim? Your contribution would be greatly appreciated.

**Comment by kurokkasu** [comment]
![qzssgood](https://user-images.githubusercontent.com/82863897/201009901-81ff17c8-9210-4db1-91a7-563467ab222c.PNG)
I tried receiving again.
Is this a success?

**Comment by IvanKor** [comment]
too bad values Residual
