### ISSUE TITLE
Please tell me how to display the map

### ISSUE THREAD

**Issue by kamitanihidetoshi** [osqzss/gps-sdr-sim#354]
![S__374480899](https://user-images.githubusercontent.com/113161317/199174010-35c4db1d-bb9c-4de0-95b9-7603444eb89b.jpg)
I don't know how to display the map. I installed Google Earth.

**Comment by Imtiaz08** [comment]
Aren't you on the wrong thread? I think this is related to GNSS-SDR and GPS SDR SIM is something different. The former is a receiver while the latter is a signal generator.

**Comment by kamitanihidetoshi** [comment]
Sorry if my understanding is wrong. This screen is GNSS-SDR. What settings should I do to display the map?

**Comment by kamitanihidetoshi** [comment]
I don't understand about Esri contributors.

**Comment by osqzss** [comment]
Wrong place to ask. Pop the question to gnss-sdr-monitor guys. 
https://github.com/acebrianjuan/gnss-sdr-monitor

**Comment by kamitanihidetoshi** [comment]
thanks!!
