### ISSUE TITLE
Trying to simulate a route with points with no GPS signal

### ISSUE THREAD

**Issue by ferorted** [osqzss/gps-sdr-sim#355]
I am trying to simulate a route with some points without GPS signal (blind points) in a motion file.
At those points, I want the simulator doesn't send any GPS signal and the GPS receiver has no signal.
My goal is to check how long it takes the GPS receiver to get back to a valid solution (fix) after being without signal for a while and receiving it again (for example a route with a tunnel in the middle).

Now I simulate those points whit:
chan[i].dataBit = 0;
chan[i].codeCA = 0;
i_acc = 0;
q_acc = 0;

But I don't know if this is a terrible way or there is a better method to simulate it.
Any way to get it right?

**Comment by ferorted** [comment]
Nothing?

**Comment by osqzss** [comment]
You don't need to set dataBit or codeCA to zero. Simply send zero I and Q by writing zero into iq_buff.
