### ISSUE TITLE
MAX_CHAN value

### ISSUE THREAD

**Issue by fener1efes2** [osqzss/gps-sdr-sim#358]
What does MAX_CHAN value define?
Which definition below is correct?

1-) Exact number of satellites that is being simulated.
For example, if I set MAX_CHAN to 5, the code will simulate 5 satellites all the time.

2-) Maximum number of satellites that is being simulated.
If I set, MAX_CHAN to 5, the code will simulate up to 5 number of satellites.
Sometimes number of simulated satellites will be 4, sometimes 5.. etc..

**Comment by osqzss** [comment]
No. 2.

**Comment by fener1efes2** [comment]
Can you give a little background?
Why does the simulation act like that, why does not always simulate 5 channels?

**Comment by osqzss** [comment]
The number of visible satellites could be less than MAX_CHAN.

**Comment by fener1efes2** [comment]
I set MAX_CHAN=1
But the GPS receiver observed more than one satellite. Why does that happen?

**Comment by Imtiaz08** [comment]
yeah I noticed some strange because I was also getting BDS satellites while receiving the signal using ublox zed F9p and hackRF one. I was feeding the signal directly via sma to sma 

maybe because of the C/A code errors IDK but I forgot to take a screenshot
