### ISSUE TITLE
ERROR: no current set of ephemerides

### ISSUE THREAD

**Issue by powerae** [osqzss/gps-sdr-sim#373]
Hi,  I am trying to generate the bin file. A folder contains the gps-sdr-sim exe and the updated brdc file but still get the following error

" ERROR: No current set of ephemerides has been found. "

How to proceed ? what am I missing ?

**Comment by powerae** [comment]
Thank you for the response. I didnt use the any T or t parameters. are they necessary ?

**Comment by powerae** [comment]
**command line:**
 \Desktop\TEST\gps-sdr-sim -e brdc1640.23n -l -57.050345, 10.532051 -b 8

**output :** 
Using static location mode.
Start time =    0/00/00,00:00:00 (0:0)
Duration = 300.0 [sec]
ERROR: No current set of ephemerides has been found.

**Comment by osqzss** [comment]
What is the RINEX version of the brdc1640.23n file? GPS-SDR-SIM can recognize only version 2.

**Comment by osqzss** [comment]
Please set latitude, longitude and hight with "-l" option without a space after comma. Run the software with only "-e" option and see how it goes.

**Comment by powerae** [comment]
the file was downloaded from here : https://cddis.nasa.gov/archive/gnss/data/daily/2023/brdc/
I think it said is rinex v2.
I tried again as with just -e and still the same output.

**Comment by osqzss** [comment]
I had no problem running the code with the same BRDC file. Please build the executable from the current master repository.

![gps-sdr-sim](https://github.com/osqzss/gps-sdr-sim/assets/7418842/cb457381-10cb-428b-b226-8fc747baf14c)

**Comment by powerae** [comment]
It worked ! This solved it . Thank you very much !
