### ISSUE TITLE
How many satellites are simulated?

### ISSUE THREAD

**Issue by HaXlezi** [osqzss/gps-sdr-sim#376]
Hi, can someone please explain, how many satellites are simulated by this SW? Is it simulating just those which could be seen from fictive location or is it just some static number of satellites?
Thank you!

**Comment by osqzss** [comment]
MAX_CHAN defines the number of channels. The default value is 16.

**Comment by HaXlezi** [comment]
Sooo... if i don´t change this thing, it will always generate singal from 16 satellites independently on selected location?

**Comment by Imtiaz08** [comment]
That's true you will have 16 channels but the number of satellites will depend on the location because the simulator picks them based on their elevation angles

**Comment by HaXlezi** [comment]
Great guys! Thank you so much
