### ISSUE TITLE
GNSS Support - Realtime GPS Data

### ISSUE THREAD

**Issue by davidscott39** [osqzss/gps-sdr-sim#38]
Hello,

Have you considered adding support for GNSS to gps-sdr-sim to include the option for realtime GPS data?

http://gnss-sdr.org/

Otherwise, does anyone know how you might precompute the brdc rinex files for future times?

Thanks!

**Comment by osqzss** [comment]
There's no plan at this point, but any contributions, but any contributions are always welcomed!

**Comment by zimler** [comment]
@davidscott39 have you looked into the Ultra-Rapid(predictive half) data type? It _seems_ like that is what that product is - a predictive file, but I'm not sure if it is available ahead of time or not... https://igscb.jpl.nasa.gov/components/prods.html

I'm trying to get real time GPS transmission, too.

**Comment by osqzss** [comment]
I added the option '-T' to overwrite the TOC and TOC in the RINEX navigation file to the user-specified scenario start time. See if it works.

**Comment by zimler** [comment]
I can try tonight, in about 8 hours. Thank you!

**Comment by zimler** [comment]
@osqzss the -T performed as expected. Thanks!

**Comment by zxcvbngg** [comment]
666
