### ISSUE TITLE
hackplayer vs hack_transfer

### ISSUE THREAD

**Issue by antmerlino** [osqzss/gps-sdr-sim#384]
Hi @osqzss 

The main page documentation instructs you to use the hackrf_transfer binary directly from the hackrf tools library.  However, there is also hackplayer from the player/ directory that aligns with all of the other SDR options.

Could you please explain the differences between the two approaches and what you would recommend? Is there any functional difference?

Thanks again for your help!

**Comment by osqzss** [comment]
They are basically the same.

**Comment by antmerlino** [comment]
Thanks @osqzss.  In that case I will just use hackrf_transfer.
