### ISSUE TITLE
Erroneous Date Calculation in GPS Receivers: Future Time Settings Misalignment

### ISSUE THREAD

**Issue by neu-aetd** [osqzss/gps-sdr-sim#399]
When I set a future date using the parameter 'T' to May 18, 2039, at 00:00:00, the GPS receiver incorrectly displays the date as October 2, 2019, at 00:00:00. This pattern continues with other future years as follows:
If the year is set to 2040, the output shifts back to 2020.
If the year is set to 2041, the output shifts back to 2021.
If the year is set to 2050, the output shifts back to 2030.
If the year is set to 2060, the output shifts back to 2020.
![2039](https://github.com/osqzss/gps-sdr-sim/assets/136040512/6e3a36e8-a1b8-4c65-b202-c5fe7b2471c0)
![Screenshot_20240521-182124](https://github.com/osqzss/gps-sdr-sim/assets/136040512/4e142947-abe0-44e1-b253-f9283e4b4ccd)
![Screenshot_20240521-182131](https://github.com/osqzss/gps-sdr-sim/assets/136040512/8aca76bc-6f38-431b-97a1-50d521cc7cd0)

**Comment by osqzss** [comment]
https://en.wikipedia.org/wiki/GPS_week_number_rollover
