### ISSUE TITLE
Geolocation does not change

### ISSUE THREAD

**Issue by Keyt13** [osqzss/gps-sdr-sim#408]
I use hackrf one great Scott gadgets (ANT500 / GPS ACTIVE ) antennas. (R8)
Checking through Android applications, gps signals are coming. Geolocation does not change. 
I did it on Kali Linux , android , windows .

The program always disconnects itself when total time 300.xxx

If you can help me solve the problem . I can explain in detail what I did and how I did it

**Comment by Keyt13** [comment]
![IMG_1943](https://github.com/user-attachments/assets/bd3c3368-5683-4eee-9224-e3b067ee4513)
![dc0ddaa35d761fe71c48219cc942c754](https://github.com/user-attachments/assets/de866b99-b1ac-4aed-b1dd-f32d0de69020)

**Comment by victor-vu-max** [comment]
Same here, really stressful

**Comment by victor-vu-max** [comment]
![Uploading IMG_UPLOAD_20240817_214032.jpg…]()

**Comment by victor-vu-max** [comment]
![IMG_UPLOAD_20240817_214032](https://github.com/user-attachments/assets/30a76cd1-4e7f-469d-8c2b-f86431097825)

**Comment by Robotix-00** [comment]
This is intended behavior, as gps-sdr-sim only generates a 300 second spoofed signal by default.
If you need more time, you can use the **-d <sec>** option when generating the .bin file and specify up to 86400s (24h).

Note that this only applies to static mode.

**Comment by victor-vu-max** [comment]
![335e0d7a-3a71-4a11-9cbd-5b7dbd6b39ef](https://github.com/user-attachments/assets/cddf57e3-2671-4392-92e3-0f6f81305e04)
![14957c9dd76d73332a7c](https://github.com/user-attachments/assets/08fa2bf1-bf38-4f36-b7aa-e7e76d3fa80a)
![Capture11](https://github.com/user-attachments/assets/503c2a44-6ee9-47a5-99c1-4aaa557f0f8d)
![Capture22](https://github.com/user-attachments/assets/01daeff5-2608-46f2-8b46-9fbe4212229d)
Geolocation does not change even i switched to flight mode on mobile

**Comment by Robotix-00** [comment]
You are not using external attenuator. The readme describes the hardware like so:
"The TX port of a particular SDR platform is connected to the GPS receiver under test through a DC block and a fixed 50-60dB attenuator."
Those are parts that need to be put in between the sdr and the antenna to achieve the right result. GPS is a very weak signal, as the satelites are quite far away, so your sdr is way stronger than your receiver could ever reasonably expect.

**Comment by victor-vu-max** [comment]
I have read about how to degrade the GPS signal emitted from the R8 antenna from the SDR. However, the GPS data on current Androin or IOS phones uses A-GPS technology and it depends on Wi-Fi or Bluetooth connections. Therefore, GPS spoofing is completely impossible with these mobile devices.

**Comment by Keyt13** [comment]
Thank you all.
With the help of Android apps I managed to change it, but the coordinates I specified are as different as possible from what I was given. 

Can you tell me what might be affecting this?

**Comment by Keyt13** [comment]
![IMG_1993](https://github.com/user-attachments/assets/020aa1e8-c767-4ef7-ae02-638b695f11c2)
![IMG_1992](https://github.com/user-attachments/assets/4dbd35d4-8869-4959-ad02-ba9172df79db)
![IMG_1991](https://github.com/user-attachments/assets/8384c757-f6a7-4674-b663-bafdc60ea849)
![IMG_1990](https://github.com/user-attachments/assets/faff0b0a-97af-48d5-9850-4289eb8f6456)
![IMG_1989](https://github.com/user-attachments/assets/39398d1c-8604-4a54-999d-f105c596bf40)

**Comment by Keyt13** [comment]
Thank you all for responding. I did it!

**Comment by Robotix-00** [comment]
You have spaces in between your location when generating the signal. Gps sim interprets those as different attributes. If you remove the spaces everything should work.
