### ISSUE TITLE
Recent BRCD files not (always) working

### ISSUE THREAD

**Issue by apppie123** [osqzss/gps-sdr-sim#413]
Strangest issue:
I've been using your code for a year now and it worked perfectly.
However, since recently it is giving me random issues.

Attached two brdc files downloaded from nasa.
brdc1150.24n.gz works as expected.
brdc2550.24n.gz sometimes works, sometimes I get an error at the start that the end time is incorrect. Max end time is some random numbers and not a date. However, when I restart then sometimes it does work.

As said, this compiled binary is running for a year without changes. Running on Ubuntu 22.04.

I also tried the multi-sdr-sim code and it has the same problem. brdc2550 gives me a segmentation 
fault, brdc1150 works fine.

I cannot find any obvious differences in the file.

[brdc2550.24n.gz](https://github.com/user-attachments/files/16978057/brdc2550.24n.gz)
[brdc1150.24n.gz](https://github.com/user-attachments/files/16978058/brdc1150.24n.gz)

**Comment by osqzss** [comment]
It could be the same issue: https://github.com/osqzss/gps-sdr-sim/issues/400

**Comment by apppie123** [comment]
> It could be the same issue: #400

Yes! Thank you so much for your super fast reply.
I set it from 13 to 15 and now it runs again with 2550.

I see you made an update 3 months ago fixing this, I totally missed it.

Thank you so much for the hard work!

**Comment by Code-Sierra** [comment]
Error opening PLUTOSDR TX device: Success (0)
Any solution for this? #412
