### ISSUE TITLE
latest build fails

### ISSUE THREAD

**Issue by crispyjones** [osqzss/gps-sdr-sim#43]
Build fails with following warnings on 14.04 and 16.04
fails on a machine with older working install 

gpssim.c: In function ‘allocateChannel’:
gpssim.c:1580:33: warning: passing argument 3 of ‘eph2sbf’ from incompatible pointer type [-Wincompatible-pointer-types]
       eph2sbf(eph[sv], ionoutc, chan[i].sbf);
                                 ^
gpssim.c:491:6: note: expected ‘long int (*)[10]’ but argument is of type ‘long unsigned int (*)[10]’
 void eph2sbf(const ephem_t eph, const ionoutc_t ionoutc, long sbf[5][N_DWRD_SBF])

**Comment by osqzss** [comment]
Does the latest source resolve the issue?

**Comment by crispyjones** [comment]
Yes, builds without warnings as expected, thank you.
