### ISSUE TITLE
Variable used before set.

### ISSUE THREAD

**Issue by luisINOV** [osqzss/gps-sdr-sim#49]
Hi Guys,
I think I have detected a small bug at "readRinexNavAll" line 983.
The variable "v" is being used before being correctly set by the PRN. Its is ;
// Date and time 
eph[ieph][sv].t = t;
// PRN
strncpy(tmp, str, 2);
tmp[2] = 0;
sv = atoi(tmp)-1;

Shouldn't be like
// PRN
strncpy(tmp, str, 2);
tmp[2] = 0;
sv = atoi(tmp)-1;
// Date and time 
eph[ieph][sv].t = t;
Is that correct ?

Thank you for the fantastic GPS sim.
Luis

**Comment by osqzss** [comment]
Yes, you're right. It's now fixed. Thank you.
