### ISSUE TITLE
Doppler shift

### ISSUE THREAD

**Issue by qarlosalberto** [osqzss/gps-sdr-sim#54]
Hello,
does gps-sdr-sim introduce the doppler effect in GPS signal?

**Comment by sundw2014** [comment]
Yes. In gpssim.c line 1312.
```
// Pseudorange rate.
rhorate = (rho1.range - chan->rho0.range)/dt;

// Carrier and code frequency.
chan->f_carr = -rhorate/LAMBDA_L1;
chan->f_code = CODE_FREQ + chan->f_carr*CARR_TO_CODE;
```
LAMBDA_L1 = 0.190293672798365 = SPEED_OF_LIGHT/GPS_L1_FREQUENCY

**Comment by qarlosalberto** [comment]
Thank you :)

2016-11-09 15:20 GMT+01:00 sundw2014 <notifications@github.com>:
