### ISSUE TITLE
Add use nav file from RTKLIB

### ISSUE THREAD

**Issue by IvanKor** [osqzss/gps-sdr-sim#56]
Dear OSQZSS !
Many thanks to you for hard work.

Is it possible to add the option to gpssim use raw-data ublox instead BRDC (brdcXXXX.XXn)
or instead use BRDC add use nav file from RTKLIB ?

RTKLIB can make from "raw-data" ublox 6,7,8 RINEX files like BRDC.

**Comment by osqzss** [comment]
gps-sdr-sim can read RINEX 2.10 navigation file. It doesn't have to be BRDC.

**Comment by IvanKor** [comment]
Thanks very much !
RINEX 2.10 works.
My question appeared as I began to try RINEX 2.12 and UP. They did not work.

I modified your real-time signal generation bladeGPS to hackrfGPS.
Windows 7, i7-4710HQ @ 2.50GHz CPU load ~ 6%   
If you want I can send you the source code hackrfGPS.

**Comment by osqzss** [comment]
That sounds nice. I am happy to test the code.

**Comment by IvanKor** [comment]
I sent the source code.
