### ISSUE TITLE
TX Antenna

### ISSUE THREAD

**Issue by patrilopez** [osqzss/gps-sdr-sim#57]
Hi all,

I want to test this software, so I would like to know what antenna I should use to transmit the signals. Could anybody recommend me an antenna to do this, or at least tell me what features should I look for in an antenna to fix this purpose?

Thanks in advance!!

**Comment by osqzss** [comment]
I am using Taoglas TS.07.0113 from Digi-Key:
http://www.digikey.com/products/en?keywords=TS.07.0113

**Comment by patrilopez** [comment]
Thank you very much!!!

**Comment by IvanKor** [comment]
GPS Helix Antenna
http://www.p4-34.com/public_html/GPSHelix.htm
