### ISSUE TITLE
multi-threaded implementation

### ISSUE THREAD

**Issue by BertK88** [osqzss/gps-sdr-sim#59]
Hello!

Is it correct that gps-sdr-sim uses 1 core only on multi-core platforms? Or did I miss something?

I've stumbled on a study that showed a CUDA-based real-time solution. Nice work.

Kind Regards,

Bert

**Comment by osqzss** [comment]
Yes, it run on a single thread. I once tried implementing multi-core processing with OpenMP, but it actually slowed down the code.
