### ISSUE TITLE
Exiting... hackrf_is_streaming() result: streaming terminated (-1004)

### ISSUE THREAD

**Issue by stackprogramer** [osqzss/gps-sdr-sim#61]
your project is great. when i test it ,with hackrf it return after some second below errors....
and i can not see changed location with gsp-receiver??
best regards stackprogramer

> root@debian:/home/admin/Documents/gps-sdr-sim-master# hackrf_transfer -t gpssim.bin -f 1575420000 -s 2600000 -a 1 -x 0
> call hackrf_set_sample_rate(2600000 Hz/2.600 MHz)
> call hackrf_set_freq(1575420000 Hz/1575.420 MHz)
> call hackrf_set_amp_enable(1)
> Stop with Ctrl-C
>  5.2 MiB / 1.015 sec =  5.2 MiB/second
>  5.2 MiB / 1.016 sec =  5.2 MiB/second
> 
>  5.2 MiB / 1.016 sec =  5.2 MiB/second
>  1.0 MiB / 1.016 sec =  1.0 MiB/second
> 
> Exiting... hackrf_is_streaming() result: streaming terminated (-1004)
> Total time: 4.06246 s
> hackrf_stop_tx() done
> hackrf_close() done
> hackrf_exit() done
> fclose(fd) done
>

**Comment by osqzss** [comment]
Try a lower sampling rate to reduce the data transfer rate.
