### ISSUE TITLE
time convert 

### ISSUE THREAD

**Issue by lk815160423** [osqzss/gps-sdr-sim#63]
dear osqzss：
        thanks for your great job. i have a question when i read the rtkcmn.c of gnss-sdrlib and the gpssim.c of gps-sdr-sim. in   #178 date2gps and #gps2date , have you ever considered the leap second. can you tell me the difference  between rtkcmn.c and gpssim.c about the time convert. thank you.

**Comment by osqzss** [comment]
The time system in gps-sdr-sim must be GPS system time. No leap second is considered.

**Comment by lk815160423** [comment]
Thanks for your answer. Maybe I need to spend more time reading the code.
On 03/27/2017 16:00, OSQZSS wrote:

The time system in gps-sdr-sim must be GPS system time. No leap second is considered.
