### ISSUE TITLE
Makefile issue on OSX (OpenMP workaround) 'omp.h' file not found

### ISSUE THREAD

**Issue by MAVProxyUser** [osqzss/gps-sdr-sim#70]
: fatal error: 'omp.h' file not found
#include <omp.h>

Some people need to use gcc version 6 in order to compile on OSX. 
"brew reinstall gcc --without-multilib" 

This is an easy workaround... 

diff --git a/Makefile b/Makefile
index 4f6933f..b260604 100644
--- a/Makefile
+++ b/Makefile
@@ -4,7 +4,12 @@
 all: gps-sdr-sim
 
 SHELL=/bin/bash
-CC=gcc
+OS := $(shell uname)
+ifeq ($(OS),Darwin)
+       CC=gcc-6
+else
+       CC=gcc
+endif
 CFLAGS=-O3 -Wall
 LDFLAGS=-lm

**Comment by osqzss** [comment]
OpenMP is not used in the code anymore. I will remove the "#include <omp.h>" line from the current version.

**Comment by MAVProxyUser** [comment]
Thanks!
