### ISSUE TITLE
TOW update in navigation message

### ISSUE THREAD

**Issue by jc1122** [osqzss/gps-sdr-sim#75]
Hello,

the navigation message in the simulation is updated every 30 s by the `generateNavMsg ` function (see lines 2264 - 2271 of gpssim.c)
```
		if (igrx%300==0) // Every 30 seconds
		{
			// Update navigation message
			for (i=0; i<MAX_CHAN; i++)
			{
				if (chan[i].prn>0)
					generateNavMsg(grx, &chan[i], 0);
			}
(...)
```

However, according to GPS specification, the TOW is updated every 6 seconds.

line 1481 of the same file:
`tow = ((unsigned long)g0.sec)/6UL;`

Just a remark.

**Comment by IvanKor** [comment]
the navigation message (1,2,3.4,5 subframe) in the simulation is updated every 30 s
