### ISSUE TITLE
RINEX V3.03 support and BDS simulator

### ISSUE THREAD

**Issue by uhwsin** [osqzss/gps-sdr-sim#76]
Hi, will this project support RINEX V3.03 and BDS?

**Comment by osqzss** [comment]
Not at this point.

**Comment by uhwsin** [comment]
Thanks!

**Comment by alkuna** [comment]
Well, I am currently working on it. I hope to PR this week.

**Comment by uhwsin** [comment]
Great news!

**Comment by DarshanNathvani** [comment]
> Well, I am currently working on it. I hope to PR this week.

Sir If Completed Please Share us, Because I Urgently Require RInex 3.03 Code.
