### ISSUE TITLE
IF signal

### ISSUE THREAD

**Issue by fabriciocscte** [osqzss/gps-sdr-sim#78]
Does this simulation generate IF signal and allows to save it in a file? I 'm developing a software receiver, so I need generates signals to test receiver sensitive.

**Comment by IvanKor** [comment]
Yes, simulation generate I/Q IF signal. IF =0;(zero IF)

**Comment by fabriciocscte** [comment]
With this config $ ./gps-sdr-sim -e brdc3540.14n -b 1 -d 30 -s 5000000
I can't acquire in my receiver. Is there a signal sample generated in this simulator to download?

**Comment by osqzss** [comment]
Try Philip's fork of SoftGNSS to test your I/Q samples:
http://sdrgps.blogspot.jp/2016/12/gps-fake-out-with-limesdr.html
https://github.com/hahnpv/SoftGNSS
