### ISSUE TITLE
Access Denied- Windows 8

### ISSUE THREAD

**Issue by hunterlit64** [osqzss/gps-sdr-sim#85]
I got the sim on windows 8, but when trying to run 
" > gps-sdr-sim -e brdc3540.14n -l 30.286502,120.032669,100 "I get "access denied" and when running as an administrator it comes up it can't be found?

**Comment by osqzss** [comment]
Make sure you run it from the command prompt. It doesn't work on the Windows PowerShell.

**Comment by hunterlit64** [comment]
Sorry, how do you mean the command prompt?  I did it by typing "cmd" in the task manager and doing it from there.

**Comment by osqzss** [comment]
It will open the command prompt. Did you run it from the folder where the gps-sdr-sim located?

**Comment by hunterlit64** [comment]
Do you mean did I click on the exercise file? It shows up with the usage options such as  -e <gps_nav>  ,etc  in the cmd" I just can't run anything from it. I'm not used to Windows.

**Comment by hunterlit64** [comment]
*exercise file* not exercise.

**Comment by hunterlit64** [comment]
exe, hate spell correct sometimes:)

**Comment by osqzss** [comment]
Type "cmd" in the address bar of the file explorer where gps-sdr-sim.exe is located.
