### ISSUE TITLE
Working on a embedded computer like Raspberry PI?

### ISSUE THREAD

**Issue by CollusW** [osqzss/gps-sdr-sim#86]
Hi, does this project suit for the embedded computer like raspberry Pi or Udoo X86? Anyone who can share some experiences? I ask this because I want to do it in real-time. I think as long as the IQ waveform generation speed is faster than the IQ sample rate, it is possible to make it real-time. Thanks!

**Comment by osqzss** [comment]
Hope you find this informative:
https://github.com/osqzss/gps-sdr-sim/issues/41

**Comment by CollusW** [comment]
Thanks for the information!
