### ISSUE TITLE
Exact condition for successful mission

### ISSUE THREAD

**Issue by EhsanArio** [osqzss/gps-sdr-sim#88]
Hi
I tested software many times with different situations. Some good and some bad results.
This is my setup :
1- Hackrf with a TCXO clock
2- a Telescopic Antenna
3- Laptop and ubuntu 16.04 running gps-sdr-sim
4- 10 Watts amplifier (in some tests)
NO attenuator is used

in some cases my phones locked and some not (GPS config set to "Device only" for all tests)
in some test there were 2 phones (Galaxy S3 and S7). S3 Locked but S7 not locked
in some other no phone locked but all GPS (in GPS Test android software) show 10 or more GPS signals and all were very good signal strength (45 to 50)

also i did some test with DJI Phantom 4 

I could spoof it in home but not outside(without amplifier)
Also could spoof my phone but could not spoof Mavic too (outside)

and ...

Now i have some guess and want to see if they are true ?

1- If signal strength goes up (35 to 50) some kind of saturation make spoofing incorrect.
2- Based on distance to our goal (Phone or Drone) we need some kind of amplifier to make signal correct level (Not below of real GPS signals and not so up to saturate)
3- Telescopic antenna may not good for this purpose
4- Why in some tests 1 phone lock but other not(both are in 1 meter distance)?
5- Why phone not lock even when they see 10 or more simulated sats ?
6- Please tell exact hardware config (Does attenuator needed ?)
7- [Here](https://github.com/op7ic/defcon-23-slides-only/blob/master/DEF%20CON%2023%20presentations/Speaker%20%26%20Workshop%20Materials/Lin%20Huang%20%26%20Qing%20Yang/DEFCON-23-Lin-Huang-Qing-Yang-GPS-Spoofing.pdf) in slide 38 says that test on phones failed because of doppler. Did you solved this problem ?
8- Commonly how much does it take to spoof a device(Phone or Drone) from start ?

any idea about above problems ?
Thanks

**Comment by osqzss** [comment]
Your question cannot be answered here because it involves intentional interference with the GPS signal.

**Comment by EhsanArio** [comment]
Hi
What do you mean by this ? Do you mean your system works only somewhere if real gps signals are absent ?

If we amplify our gps signals our targets can see our gps signal ok ?

Solving interference is a software concept or communication concept?

Any solution ?

**Comment by bitdust** [comment]
it's illegal.

**Comment by EhsanArio** [comment]
In your country may be but in mine not

**Comment by robellebor** [comment]
@osqzss "Your question cannot be answered here because it involves intentional interference with the GPS signal."  

Isn't that the main idea of this project ??? spoofing ???

**Comment by Honky103** [comment]
The main idea is to create a cheap gps signal simulator for receiver testing, not to use as a spoofer
