### ISSUE TITLE
Questions about initialize carrier phase.

### ISSUE THREAD

**Issue by uBZY** [osqzss/gps-sdr-sim#91]
I'm new to gnss development and I'm confused about the carrier phase initialization. Is it necessary?
The function `allocateChannel()`, line 1620, `phase_ini = (2.0*r_ref - r_xyz)/LAMBDA_L1;`, why initialize carrier phase like this way. According to this line, all satellites' carrier phase will be renewed after 12hours (when it's appear to be visible again), which might cause problems and consistency might be broken.
Or it's common knowledge for the community, can someone show me the reference? thx.

**Comment by osqzss** [comment]
https://github.com/osqzss/gps-sdr-sim/issues/60

**Comment by uBZY** [comment]
Thanks, that answers my question.
