### ISSUE TITLE
About prolonging 0.1 second update interval

### ISSUE THREAD

**Issue by CollusW** [osqzss/gps-sdr-sim#94]
The gps-sdr-sim updates parameters such as pseudorange and Doppler shift every 0.1 seconds. I wonder why choosing 0.1 seconds? 

In fact, I tried to change this time interval to 0.2s to reduce the calculation load for some weak CPUs. However, the receiver may not get fixed in some tests or get lost (unfixed) for several seconds after fix.

I wonder this 0.1 seconds update interval cannot be prolonged theoretically, or it is due to my code bug? If latter case, could you help review my code? Many thanks!

**Comment by osqzss** [comment]
During the update interval, it is assumed that the Doppler is constant and the pseudorange is linearly evolving. The shorter the update interval, the smaller the error. I chose 0.1 seconds to keep the pseudorange error small enough even in a high dynamics scenario. I think 0.2s should work for stationary antennas.

**Comment by CollusW** [comment]
ok, thanks. I will do some experiments with the program to record the pseudorange and Doppler and see how fast it changes. I will come back with the results later.

**Comment by CollusW** [comment]
Hi osqzss,

I modified the code to print out the pseudorange and Doppler to files (duration is set to 10s), read the values which changes every 0.1s and plotted with Matlab. 
I also checked the how much the pseudorange and Doppler changed during the 10s.
I tested under several time and location scenarios.

The detailed results are as follows.
1. pseudorange vs. time
![pseudorange](https://user-images.githubusercontent.com/21992812/32306160-b75253f4-bfb4-11e7-91bb-5106c2be2a28.png)

2. Doppler vs. time
![doppler](https://user-images.githubusercontent.com/21992812/32306183-d52964c6-bfb4-11e7-808b-7a7c466798d3.png)

You can see they are almost flat during the 10s. For other test cases, the figures are almost the same and I do not show here, where the pseudorange and Doppler are almost flat.  Further, I find the max and min value for each PRN and calculate the percentage it changes ( (max-min)/min*100% ). The results are show in the table below. 

Table. Change rate in 10 second
![table](https://user-images.githubusercontent.com/21992812/32306819-4618e956-bfb8-11e7-91b1-408d967450b3.PNG)

some conclusions from the results:
During 10 seconds, 
1. The pseudorange changed within 7000m, the change rate is less than 0.05%;
2. Doppler changed within 10Hz, the change rate is less than 15%. (Note: worst case is test case #8 with 12%. However, this is due to the small Doppler value (~25Hz) )

Assuming linear change during the 10s, the doppler changes within 0.2s shall not exceed 0.3%. I think this is small enough to relax the update interval from 0.1s to 0.2s. And we can make it even longer so that some less powerful CPUs can calculate in real time.

What do you think?

**Comment by CollusW** [comment]
Hi @osqzss ,

I upload the modified code to my gitHub (https://github.com/CollusW/gps-sdr-sim.git). It changed to 0.2s update interval. I believe it should work according to the above tests. However, as mentioned before, the receiver may not get fixed in some tests or get lost (unfixed) for several seconds after fix.

Could you pls help review the code and check if anything I missed?

Many thanks!

**Comment by osqzss** [comment]
I took a quick look at your code. One thing I noticed that the navigation message was not renewed every 30 seconds with 0.2 update interval. In this case, the igrx counter of 150 is equal to 30 seconds.

**Comment by CollusW** [comment]
I followed your advice and update the code. Then, the issue is fixed (receiver fixed successfully and no unstable issue occurs). Thanks!

btw, regarding the max update interval, the receiver's code tracking loop may get lost if the pseudorange changes too fast. Usually, the code loop requires the change of pseudorange within 1 C/A chip, which corresponds to about **0.4s** according to the simulation.

**Comment by osqzss** [comment]
Thank you for your insight.
