### ISSUE TITLE
Output file size is limited to 2GB on some 32-bit systems (Raspbian Stretch for example)

### ISSUE THREAD

**Issue by ingenico-zanetti** [osqzss/gps-sdr-sim#95]
When building on Raspbian Stretch with the provided Makefile, the executable is not capable of creating file larger than 2GB. Simply adding -D_FILE_OFFSET_BITS=64 to CFLAGS in the Makefile solves the issue (at least on Raspbian Stretch).

**Comment by osqzss** [comment]
https://github.com/osqzss/gps-sdr-sim/pull/98
