### ISSUE TITLE
Allow to use stdout as output file.

### ISSUE THREAD

**Issue by ingenico-zanetti** [osqzss/gps-sdr-sim#96]
Using the usual convention, passing - (minus / dash) as output file name instruct the program to use stdout as ouput. This allows to pipe the output directly in an SDR player accepting stdin as sample input. This means that printf(XXX) needs to be changed to fprintf(stderr, XXX) first. Usefull option as this wonderful tool is fast enough to provide more than realtime IQ samples on a Raspberry Pi 3, as far as sample rate is kept at only 1 Msps.

**Comment by osqzss** [comment]
https://github.com/osqzss/gps-sdr-sim/pull/98
