### ISSUE TITLE
Is there a way to know the satellites that will be generated ???

### ISSUE THREAD

**Issue by robellebor** [osqzss/gps-sdr-sim#99]
It would be better if we can generate the SV that we want .

**Comment by osqzss** [comment]
http://www.taroz.net/GNSS-Radar.html

**Comment by robellebor** [comment]
by the way ... is doppler effect added in the code ???

**Comment by osqzss** [comment]
https://github.com/osqzss/gps-sdr-sim/issues/54

**Comment by robellebor** [comment]
thanks
